# Generated by Django 6.0.5 on 2026-05-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercluster',
            name='onet_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
