# Generated by Django 6.0.5 on 2026-06-03 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careercluster_onet_code'),
        ('profiles', '0003_student_transcript_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('questions', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('score_profile', models.JSONField(default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to='profiles.student')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careerassessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteCareer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careercluster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_careers', to='profiles.student')),
            ],
            options={
                'unique_together': {('student', 'career')},
            },
        ),
    ]
