# Generated by Django 6.0.5 on 2026-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_advisormessage_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisormessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
