# Generated by Django 6.0.5 on 2026-06-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='transcript_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
