# Generated by Django 6.0.5 on 2026-06-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_student_transcript_text'),
        ('skills', '0003_studentcertification_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprograms',
            name='program_skills',
            field=models.ManyToManyField(blank=True, related_name='academic_programs', to='skills.skill'),
        ),
    ]
