# Generated by Django 6.0.5 on 2026-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='skills.skill'),
        ),
    ]
