# Generated by Django 6.0.5 on 2026-06-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_certification_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcertification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
