# Generated by Django 6.0.5 on 2026-06-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_studentcertification_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcertification',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Planning', max_length=50),
        ),
    ]
