# Generated by Django 6.0.5 on 2026-06-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='role_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='internship',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='type',
            field=models.CharField(default='Full-time', max_length=100),
        ),
        migrations.AddField(
            model_name='internship',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
