# Generated by Django 6.0.5 on 2026-05-22 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_initial'),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIntervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('intervention_type', models.CharField(choices=[('Skill Bridging', 'Skill Bridging'), ('GPA Improvement', 'GPA Improvement'), ('Career Counseling', 'Career Counseling'), ('Academic Guidance', 'Academic Guidance')], default='Academic Guidance', max_length=50)),
                ('notes', models.TextField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='advisors.advisor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='profiles.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
