# Generated by Django 6.0.5 on 2026-06-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0004_alter_studentintervention_intervention_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentintervention',
            name='intervention_type',
            field=models.CharField(choices=[('Skill Bridging', 'Skill Bridging'), ('GPA Improvement', 'GPA Improvement'), ('Career Counseling', 'Career Counseling'), ('Academic Guidance', 'Academic Guidance'), ('Academic Counseling', 'Academic Counseling'), ('Skills Training Recommended', 'Skills Training Recommended'), ('Career Track Updated', 'Career Track Updated'), ('Email Warning Sent', 'Email Warning Sent'), ('Report Shared', 'Report Shared')], default='Academic Guidance', max_length=50),
        ),
    ]
